# Generated by sila2.code_generator; sila2.__version__: 0.12.2
from __future__ import annotations

from typing import Set

from sila2.client import SilaClient
from sila2.framework import FullyQualifiedFeatureIdentifier

from . import dataitemprovider


class Client(SilaClient):

    DataItemProvider: dataitemprovider.DataItemProviderClient

    _expected_features: Set[FullyQualifiedFeatureIdentifier] = {
        FullyQualifiedFeatureIdentifier("org.silastandard/core/SiLAService/v1"),
        FullyQualifiedFeatureIdentifier("org.silastandard/examples/DataItemProvider/v1"),
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._register_defined_execution_error_class(
            dataitemprovider.DataItemProviderFeature.defined_execution_errors["DataNamespaceAlreadyExists"],
            dataitemprovider.DataNamespaceAlreadyExists,
        )

        self._register_defined_execution_error_class(
            dataitemprovider.DataItemProviderFeature.defined_execution_errors["DataNamespaceNameDoesNotExist"],
            dataitemprovider.DataNamespaceNameDoesNotExist,
        )

        self._register_defined_execution_error_class(
            dataitemprovider.DataItemProviderFeature.defined_execution_errors["DataCollectionAlreadyExists"],
            dataitemprovider.DataCollectionAlreadyExists,
        )

        self._register_defined_execution_error_class(
            dataitemprovider.DataItemProviderFeature.defined_execution_errors["DataCollectionDoesNotExists"],
            dataitemprovider.DataCollectionDoesNotExists,
        )

        self._register_defined_execution_error_class(
            dataitemprovider.DataItemProviderFeature.defined_execution_errors["DataItemDoesNotExists"],
            dataitemprovider.DataItemDoesNotExists,
        )
